### ISSUE TITLE
Unclear in the documentation, please update

### ISSUE THREAD

**Issue by Jegeva** [badgeek/svg2shenzhen#66] opened 2020-02-11 14:30 UTC
The extention contains a CLI version for the png2composant executable. If it is not chmod+x'ed underlinux, any layer that is enabled and relying on a component creation will make the export crash due to the .kicad_mod not existing.

chmod +x 'ing the executable solves the problem but it should be clear in the install doc.

**Comment by kasbah** [comment] 2020-02-12 20:40
Thanks for reporting but it's a duplicate of #2 (oh, it's closed :thinking: ?) and #52

**Closed as completed by kasbah** 2020-02-12 20:40 UTC
